### ISSUE TITLE
ipaddress.AddressValueError: Expected 4 octets in 'eth0'

### ISSUE THREAD

**Issue by Kartik192192** [JohnHammond/msdt-follina#5]
Traceback (most recent call last):
  File "/root/Desktop/msdt-follina/follina.py", line 63, in main
    serve_host = ipaddress.IPv4Address(args.interface)
  File "/usr/lib/python3.9/ipaddress.py", line 1307, in __init__
    self._ip = self._ip_int_from_string(addr_str)
  File "/usr/lib/python3.9/ipaddress.py", line 1194, in _ip_int_from_string
    raise AddressValueError("Expected 4 octets in %r" % ip_str)
ipaddress.AddressValueError: Expected 4 octets in 'eth0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/Desktop/msdt-follina/follina.py", line 166, in <module>
    main(parser.parse_args())
  File "/root/Desktop/msdt-follina/follina.py", line 66, in main
    serve_host = netifaces.ifaddresses(args.interface)[netifaces.AF_INET][0][
KeyError: 2

**Comment by codethinki** [comment]
You need to run it with LAN, fixed the issue for me. I don't know how to run it with wifi but that is probably going to be fixed in a few days.

**Comment by User-123447** [comment]
It's not fixed yet.. :(

**Comment by niceboy83** [comment]
just specifiy your ip adress: python follina.py -i 192.168.X.X. It works for me
