### ISSUE TITLE
Reverse connection not working properly

### ISSUE THREAD

**Issue by Cvetaca** [JohnHammond/msdt-follina#6]
I am hitting this error when trying to reverse connect to my server. Could it be outdated python problem or is it something wrong with the code?

```
python3 follina.py  -i 10.10.10.106
[+] copied staging doc /tmp/yyfwqh86
[+] created maldoc ./follina.doc
[+] serving html payload on :8000
----------------------------------------
Exception happened during processing of request from ('10.10.10.101', 13406)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 320, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 351, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "follina.py", line 134, in __init__
    super().__init__(*args, directory=serve_path, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'directory'

This repeats several times
```

**Comment by Cvetaca** [comment]
> I am hitting this error when trying to reverse connect to my server. Could it be outdated python problem or is it something wrong with the code?
> 
> ```
> python3 follina.py  -i 10.10.10.106
> [+] copied staging doc /tmp/yyfwqh86
> [+] created maldoc ./follina.doc
> [+] serving html payload on :8000
> ----------------------------------------
> Exception happened during processing of request from ('10.10.10.101', 13406)
> Traceback (most recent call last):
>   File "/usr/lib/python3.6/socketserver.py", line 320, in _handle_request_noblock
>     self.process_request(request, client_address)
>   File "/usr/lib/python3.6/socketserver.py", line 351, in process_request
>     self.finish_request(request, client_address)
>   File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
>     self.RequestHandlerClass(request, client_address, self)
>   File "follina.py", line 134, in __init__
>     super().__init__(*args, directory=serve_path, **kwargs)
> TypeError: __init__() got an unexpected keyword argument 'directory'
> 
> This repeats several times
> ```

It requires python 3.9+
